#!/bin/bash

# Print commands
set -x

if [ ! -s "$FILE_SITE_VCL" ]; then    
    bash "$FILE_GENERATE_SITE_VCL_SH" > "$FILE_SITE_VCL"
fi

# Start varnish
varnishd -a :"$VARNISH_HTTP_PORT" -f "$FILE_DEFAULT_VCL" -s "malloc,$VARNISH_MEM" -p "vsl_mask=${VARNISH_VSL_MASK_HASH:+"+Hash"}"

# Write varnish log to /var/log/varnish/varnish.log
exec varnishlog
