#!/bin/bash

# Print commands
set -x

if [ ! -e "$FILE_SITE_VCL" ] || [ "$(cat "$FILE_SITE_VCL")" == "" ]; then    
    bash "$FILE_GENERATE_SITE_VCL_SH" > "$FILE_SITE_VCL"
fi

# Make sure log file exists
touch "$FILE_LOG_VARNISH"

# Start varnish
varnishd -f "$FILE_DEFAULT_VCL" -s "malloc,$VARNISH_MEM"

# Write varnish log to /var/log/varnish/varnish.log
varnishlog
